Repository FabricMC/fabric-docs, pull requests merged in 2024-01, with the labels that each got.

#5 Player Guides
  .gitignore
  .vitepress/config.mts
  .vitepress/theme/style.css
  assets/players/crash-report-example.txt
  assets/players/installing-fabric/installer-screen.png
  assets/players/installing-fabric/launcher-screen.png
  assets/players/installing-fabric/macos-downloads.png
  assets/players/installing-java/linux-java-version.png
  assets/players/installing-java/windows-download-java.png
  assets/players/installing-java/windows-java-version.png
  assets/players/installing-java/windows-run-dialog.png
  assets/players/installing-java/windows-wizard-screenshot.png
  assets/players/installing-mods.png
  assets/players/updating-fabric.png
  index.md
  players/faq.md
  players/finding-mods.md
  players/index.md
  players/installing-fabric.md
  players/installing-java/linux.md
  players/installing-java/windows.md
  players/installing-mods.md
  players/troubleshooting/crash-reports.md
  players/troubleshooting/uploading-logs.md
  players/updating-fabric.md
  sidebars.json
Labels: content

#15 Sidebar, SEO and Sitemap
  .gitignore
  .vitepress/config.mts
  .vitepress/seo.ts
  .vitepress/sidebars/players.ts
  .vitepress/sidebars/root.ts
  index.md
  public/favicon.png
  public/logo.png
Labels: framework

#19 Snippet Extension Plugin
  .vitepress/config.mts
  package-lock.json
  package.json
Labels: framework

#18 Codec Guide
  develop/codecs.md
  reference/latest/src/main/java/com/example/docs/codec/Bean.java
  reference/latest/src/main/java/com/example/docs/codec/BeanType.java
  reference/latest/src/main/java/com/example/docs/codec/BeanTypes.java
  reference/latest/src/main/java/com/example/docs/codec/CountingBean.java
  reference/latest/src/main/java/com/example/docs/codec/StringyBean.java
Labels: content, merge-please

#20 "Creating Custom Particles" Page
  develop/particles/creating-particles.md
  reference/latest/src/client/java/com/example/docs/FabricDocsReferenceClient.java
  reference/latest/src/main/java/com/example/docs/FabricDocsReference.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/particles/my_particle.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/particle/myparticletexture.png
Labels: content, merge-please

#21 Author System
  .vitepress/theme/components/PageAuthorComponent.vue
  .vitepress/theme/index.ts
  CONTRIBUTING.md
  players/finding-mods.md
  players/installing-fabric.md
  players/installing-java/linux.md
  players/installing-java/windows.md
  players/installing-mods.md
  players/troubleshooting/crash-reports.md
  players/troubleshooting/uploading-logs.md
  players/updating-fabric.md
Labels: merge-please, framework

#22 Events Guide
  develop/events.md
  reference/latest/src/main/java/com/example/docs/event/FabricDocsReferenceEvents.java
  reference/latest/src/main/java/com/example/docs/event/SheepShearCallback.java
  reference/latest/src/main/java/com/example/docs/mixin/event/SheepEntityMixin.java
  reference/latest/src/main/resources/fabric-docs-reference.mixins.json
  reference/latest/src/main/resources/fabric.mod.json
Labels: content, merge-please

#25 Use fork of markdown-snippet that fixes indents.
  develop/events.md
  package-lock.json
  package.json
Labels: merge-please, framework
