Repository FabricMC/fabric-docs, pull requests merged in 2024-02, with the labels that each got.

#26 Command Guides
  assets/develop/commands/custom-arguments_fail.png
  assets/develop/commands/custom-arguments_result.png
  assets/develop/commands/custom-arguments_valid.png
  develop/commands/arguments.md
  develop/commands/basics.md
  develop/commands/suggestions.md
  reference/latest/src/client/java/com/example/docs/client/command/FabricDocsReferenceClientCommands.java
  reference/latest/src/main/java/com/example/docs/command/BlockPosArgumentType.java
  reference/latest/src/main/java/com/example/docs/command/FabricDocsReferenceCommands.java
  reference/latest/src/main/java/com/example/docs/command/PlayerSuggestionProvider.java
  reference/latest/src/main/resources/fabric.mod.json
Labels: content, cleanup-stage

#28 Effects and Potions Guides
  assets/develop/tater-effect.png
  assets/develop/tater-potion.png
  develop/effects.md
  develop/potions.md
  reference/latest/src/main/java/com/example/docs/effect/FabricDocsReferenceEffects.java
  reference/latest/src/main/java/com/example/docs/effect/TaterEffect.java
  reference/latest/src/main/java/com/example/docs/mixin/potion/BrewingRecipeRegistryInvoker.java
  reference/latest/src/main/java/com/example/docs/potion/FabricDocsReferencePotions.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/lang/en_us.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/mob_effect/tater.png
  reference/latest/src/main/resources/fabric-docs-reference.mixins.json
  reference/latest/src/main/resources/fabric.mod.json
Labels: content, merge-please, cleanup-stage

#24 Rendering Guides
  assets/develop/rendering/concepts-matrix-stack.webp
  assets/develop/rendering/concepts-practical-example-draw-process.png
  assets/develop/rendering/concepts-practical-example-final-result.png
  assets/develop/rendering/concepts-quaternions.webp
  assets/develop/rendering/draw-context-lines.png
  assets/develop/rendering/draw-context-recipe-book-background.png
  assets/develop/rendering/draw-context-rectangle-border.png
  assets/develop/rendering/draw-context-rectangle.png
  assets/develop/rendering/draw-context-region-texture.png
  assets/develop/rendering/draw-context-scissor.png
  assets/develop/rendering/draw-context-text.png
  assets/develop/rendering/draw-context-whole-texture.png
  assets/develop/rendering/gui/custom-1-example.png
  assets/develop/rendering/gui/custom-widget-events.webp
  assets/develop/rendering/gui/custom-widget-example.png
  assets/develop/rendering/hud-rendering-deltatick.webp
  develop/rendering/basic-concepts.md
  develop/rendering/draw-context.md
  develop/rendering/gui/custom-screens.md
  develop/rendering/gui/custom-widgets.md
  develop/rendering/hud.md
  reference/latest/src/client/java/com/example/docs/mixin/client/TitleScreenMixin.java
  reference/latest/src/client/java/com/example/docs/rendering/DrawContextExampleScreen.java
  reference/latest/src/client/java/com/example/docs/rendering/HudRenderingEntrypoint.java
  reference/latest/src/client/java/com/example/docs/rendering/RenderingConceptsEntrypoint.java
  reference/latest/src/client/java/com/example/docs/rendering/screens/CustomScreen.java
  reference/latest/src/client/java/com/example/docs/rendering/screens/CustomWidget.java
  reference/latest/src/client/resources/fabric-docs-reference.client.mixins.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/gui/test-uv-drawing.png
  reference/latest/src/main/resources/fabric.mod.json
Labels: content, cleanup-stage

#38 Warning Banner
  .vitepress/theme/components/BannerComponent.vue
  .vitepress/theme/index.ts
Labels: framework

#40 Translation tweaks
  .github/workflows/build.yml
  .vitepress/config.mts
  crowdin.yml
  es/.gitkeep
  package-lock.json
  package.json
Labels: framework

#43 Asset handling fixes.
  develop/commands/arguments.md
  develop/entities/effects.md
  develop/items/potions.md
  develop/rendering/basic-concepts.md
  develop/rendering/draw-context.md
  develop/rendering/gui/custom-screens.md
  develop/rendering/gui/custom-widgets.md
  develop/rendering/hud.md
  public/assets/develop/commands/custom-arguments_fail.png
  public/assets/develop/commands/custom-arguments_result.png
  public/assets/develop/commands/custom-arguments_valid.png
  public/assets/develop/rendering/concepts-matrix-stack.webp
  public/assets/develop/rendering/concepts-practical-example-draw-process.png
  public/assets/develop/rendering/concepts-practical-example-final-result.png
  public/assets/develop/rendering/concepts-quaternions.webp
  public/assets/develop/rendering/draw-context-lines.png
  public/assets/develop/rendering/draw-context-recipe-book-background.png
  public/assets/develop/rendering/draw-context-rectangle-border.png
  public/assets/develop/rendering/draw-context-rectangle.png
  public/assets/develop/rendering/draw-context-region-texture.png
  public/assets/develop/rendering/draw-context-scissor.png
  public/assets/develop/rendering/draw-context-text.png
  public/assets/develop/rendering/draw-context-whole-texture.png
  public/assets/develop/rendering/gui/custom-1-example.png
  public/assets/develop/rendering/gui/custom-widget-events.webp
  public/assets/develop/rendering/gui/custom-widget-example.png
  public/assets/develop/rendering/hud-rendering-deltatick.webp
  public/assets/develop/tater-effect.png
  public/assets/develop/tater-potion.png
  public/assets/players/crash-report-example.txt
  public/assets/players/installing-fabric/installer-screen.png
  public/assets/players/installing-fabric/launcher-screen.png
  public/assets/players/installing-fabric/macos-downloads.png
  public/assets/players/installing-java/linux-java-version.png
  public/assets/players/installing-java/windows-download-java.png
  public/assets/players/installing-java/windows-java-version.png
  public/assets/players/installing-java/windows-run-dialog.png
  public/assets/players/installing-java/windows-wizard-screenshot.png
  public/assets/players/installing-mods.png
  public/assets/players/updating-fabric.png
Labels: merge-please, framework

#44 Dynamic locales + sidebar translations.
  .vitepress/config.mts
  .vitepress/i18n.ts
  .vitepress/sidebars/develop.ts
  .vitepress/sidebars/es/players.ts
  .vitepress/sidebars/es/root.ts
  .vitepress/sidebars/players.ts
  .vitepress/sidebars/root.ts
  .vitepress/sidebars/utils.ts
  crowdin.yml
  package-lock.json
  package.json
  sidebar_translations.json
  sidebars.json
  translated/.gitkeep
Labels: framework

#46 Locale Loading Fix
  .vitepress/i18n.ts
Labels: merge-please, framework

#54 Locale sidebar URL fixes.
  .vitepress/i18n.ts
Labels: merge-please, framework

#55 Ignore language if index.md is missing.
  .vitepress/config.mts
  .vitepress/i18n.ts
Labels: merge-please, framework

#57 Small player-facing fixes
  players/installing-java/linux.md
  players/troubleshooting/crash-reports.md
Labels: improvement, content, merge-please

#62 small fixes in texts
  players/faq.md
  players/installing-java/linux.md
  players/troubleshooting/uploading-logs.md
Labels: improvement
