Repository FabricMC/fabric-docs, pull requests merged in 2024-07, with the labels that each got.

#118 Blocks
  .vitepress/sidebars/develop.ts
  develop/blocks/blockstates.md
  develop/blocks/first-block.md
  public/assets/develop/blocks/blockstates_0_large.png
  public/assets/develop/blocks/blockstates_1.png
  public/assets/develop/blocks/blockstates_2_large.png
  public/assets/develop/blocks/blockstates_3.webm
  public/assets/develop/blocks/condensed_oak_log_textures.zip
  public/assets/develop/blocks/first_block_0.png
  public/assets/develop/blocks/first_block_1.png
  public/assets/develop/blocks/first_block_1_small.png
  public/assets/develop/blocks/first_block_4.png
  public/assets/develop/blocks/prismarine_lamp_textures.zip
  reference/latest/src/main/java/com/example/docs/block/FabricDocsReferenceBlocks.java
  reference/latest/src/main/java/com/example/docs/block/ModBlocks.java
  reference/latest/src/main/java/com/example/docs/block/custom/PrismarineLampBlock.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/blockstates/condensed_dirt.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/blockstates/condensed_oak_log.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/blockstates/prismarine_lamp.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/lang/en_us.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/condensed_dirt.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/condensed_oak_log.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/condensed_oak_log_horizontal.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/prismarine_lamp.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/prismarine_lamp_on.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/item/condensed_dirt.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/item/condensed_oak_log.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/item/prismarine_lamp.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/condensed_oak_log.png
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/condensed_oak_log_top.png
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/prismarine_lamp.png
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/prismarine_lamp_on.png
  reference/latest/src/main/resources/data/fabric-docs-reference/loot_tables/blocks/condensed_dirt.json
  reference/latest/src/main/resources/data/minecraft/tags/mineable/shovel.json
  reference/latest/src/main/resources/fabric.mod.json
  sidebar_translations.json
Labels: content, merge-please

#136 Fix indentation for ModArmorMaterials.java
  reference/latest/src/main/java/com/example/docs/item/armor/ModArmorMaterials.java
Labels: improvement, merge-please

#135 improve order for ModItems tutorial
  reference/latest/src/main/java/com/example/docs/item/ModItems.java
Labels: improvement, merge-please

#137 Hotswapping with JBR
  develop/getting-started/launching-the-game.md
  translated/de_de/develop/getting-started/launching-the-game.md
Labels: improvement, merge-please

#145 "Using the ide" Page [Part 2]
  .gitignore
  .vitepress/sidebars/develop.ts
  develop/ide-tips-and-tricks.md
  public/assets/develop/misc/using-the-ide/analyzing_01.png
  public/assets/develop/misc/using-the-ide/analyzing_02.png
  public/assets/develop/misc/using-the-ide/analyzing_03.png
  public/assets/develop/misc/using-the-ide/comments_01.png
  public/assets/develop/misc/using-the-ide/comments_02.png
  public/assets/develop/misc/using-the-ide/comments_03.png
  public/assets/develop/misc/using-the-ide/comments_04.png
  public/assets/develop/misc/using-the-ide/comments_05.png
  public/assets/develop/misc/using-the-ide/comments_06.png
  public/assets/develop/misc/using-the-ide/comments_07.png
  public/assets/develop/misc/using-the-ide/refactoring_01.png
  public/assets/develop/misc/using-the-ide/search_and_replace_01.png
  public/assets/develop/misc/using-the-ide/traversing_01.png
  public/assets/develop/misc/using-the-ide/traversing_02_1.png
  public/assets/develop/misc/using-the-ide/traversing_02_2.png
  public/assets/develop/misc/using-the-ide/traversing_03.png
  public/assets/develop/misc/using-the-ide/traversing_04.png
  public/assets/develop/misc/using-the-ide/traversing_05.png
  public/assets/develop/misc/using-the-ide/traversing_06.png
  public/assets/develop/misc/using-the-ide/util_01.png
  public/assets/develop/misc/using-the-ide/util_02.png
  sidebar_translations.json
Labels: content, merge-please

#146 Fixed author listings for JR1811 pages
  develop/ide-tips-and-tricks.md
  develop/sounds/using-sounds.md
Labels: bug, inconsistency, merge-please

#144 Add "Custom Data Components" page to Item section
  .vitepress/sidebars/develop.ts
  develop/items/custom-data-components.md
  public/assets/develop/items/custom_component_0.png
  public/assets/develop/items/custom_component_1.png
  public/assets/develop/items/custom_component_2.png
  public/assets/develop/items/custom_component_3.png
  public/assets/develop/items/custom_component_4.png
  public/assets/develop/items/custom_component_5.png
  public/assets/develop/items/custom_component_6.png
  public/assets/develop/items/custom_component_7.png
  reference/latest/src/main/java/com/example/docs/component/FabricDocsReferenceComponents.java
  reference/latest/src/main/java/com/example/docs/component/ModComponents.java
  reference/latest/src/main/java/com/example/docs/component/MyCustomComponent.java
  reference/latest/src/main/java/com/example/docs/item/ModItems.java
  reference/latest/src/main/java/com/example/docs/item/custom/CounterItem.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/lang/en_us.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/item/counter.json
  reference/latest/src/main/resources/fabric.mod.json
  sidebar_translations.json
Labels: content, last-call

#152 Fix armor items for 1.21
  develop/items/custom-armor.md
  reference/latest/src/main/java/com/example/docs/item/ModItems.java
  reference/latest/src/main/java/com/example/docs/item/armor/ModArmorMaterials.java
Labels: improvement, merge-please
