Repository FabricMC/fabric-docs, pull requests merged in 2024-03, with the labels that each got.

#67 Small Fix
  players/faq.md
  players/finding-mods.md
  players/installing-fabric.md
  players/installing-mods.md
  players/troubleshooting/crash-reports.md
  players/troubleshooting/uploading-logs.md
  sidebar_translations.json
Labels: improvement, merge-please, cleanup-stage

#61 Creating Custom Particles Guide Overhaul
  develop/rendering/particles/creating-particles.md
  public/assets/develop/rendering/particles/sparkle-particle-showcase.png
  reference/latest/src/client/java/com/example/docs/FabricDocsReferenceClient.java
  reference/latest/src/main/java/com/example/docs/FabricDocsReference.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/particles/my_particle.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/particles/sparkle_particle.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/particle/myparticletexture.png
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/particle/sparkle_particle_texture.png
Labels: improvement, cleanup-stage

#66 Contributing page update
  CONTRIBUTING.md
Labels: framework, cleanup-stage

#50 Damage Types Guide
  .vitepress/sidebars/develop.ts
  develop/entities/damage-types.md
  public/assets/develop/tater-damage-death.png
  reference/latest/src/main/generated/data/fabric-docs-reference/damage_type/tater.json
  reference/latest/src/main/generated/data/minecraft/tags/damage_type/bypasses_armor.json
  reference/latest/src/main/java/com/example/docs/damage/FabricDocsReferenceDamageTypes.java
  reference/latest/src/main/java/com/example/docs/damage/FabricDocsReferenceDamageTypesDataGenerator.java
  reference/latest/src/main/java/com/example/docs/damage/TaterBlock.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/blockstates/tater.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/lang/en_us.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/tater.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/item/tater.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/tater.png
  reference/latest/src/main/resources/fabric.mod.json
  sidebar_translations.json
Labels: content, merge-please, cleanup-stage

#68 Sounds Pages
  .vitepress/sidebars/develop.ts
  .vscode/settings.json
  develop/sounds/custom.md
  develop/sounds/using-sounds.md
  public/assets/develop/sounds/custom_sounds_0.png
  public/assets/develop/sounds/custom_sounds_1.png
  public/assets/develop/sounds/custom_sounds_2.png
  public/assets/develop/sounds/custom_sounds_3.png
  reference/latest/src/main/java/com/example/docs/item/CustomSoundItem.java
  reference/latest/src/main/java/com/example/docs/item/FabricDocsReferenceItems.java
  reference/latest/src/main/java/com/example/docs/sound/CustomSounds.java
  reference/latest/src/main/java/com/example/docs/sound/FabricDocsReferenceSounds.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/lang/en_us.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/sounds.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/sounds/metal_whistle.ogg
  reference/latest/src/main/resources/fabric.mod.json
  sidebar_translations.json
Labels: content, merge-please

#77 Fix Codeowners file.
  .github/CODEOWNERS
Labels: merge-please, framework

#79 Codeowner Fix
  .github/CODEOWNERS
Labels: merge-please, framework

#78 Exclude regional variants of languages on crowdin.
  crowdin.yml
Labels: merge-please, framework

#76 Remove incorrect special case for when commands return zero
  develop/commands/basics.md
Labels: improvement, content, merge-please

#75 Add recursive codec guide
  develop/codecs.md
Labels: improvement, content, merge-please
