Repository FabricMC/fabric-docs, pull requests merged in 2024-12, with the labels that each got.

#182 Additional translatable text information
  develop/text-and-translations.md
Labels: improvement, stage:ready

#191 update ide tips and tricks
  develop/ide-tips-and-tricks.md
Labels: improvement, stage:ready

#235 ide tips 2: electric boogaloo (here we go again)
  develop/ide-tips-and-tricks.md
  public/assets/develop/misc/using-the-ide/context_actions_01.png
  public/assets/develop/misc/using-the-ide/context_actions_02.png
Labels: correction, stage:ready

#224 Refactored Tater Effect registration and updated docs
  develop/entities/effects.md
  reference/latest/src/main/java/com/example/docs/ReferenceMethods.java
  reference/latest/src/main/java/com/example/docs/effect/FabricDocsReferenceEffects.java
  reference/latest/src/main/java/com/example/docs/potion/FabricDocsReferencePotions.java
Labels: improvement, stage:ready

#237 the intellij documentation links in ide-tips-and-tricks dont actually work without the .html
  develop/ide-tips-and-tricks.md
Labels: correction, stage:ready

#238 Block Entities article
  .vitepress/sidebars/develop.ts
  develop/blocks/block-entities.md
  public/assets/develop/blocks/block_entities_1.png
  reference/latest/src/main/java/com/example/docs/block/ModBlocks.java
  reference/latest/src/main/java/com/example/docs/block/custom/CounterBlock.java
  reference/latest/src/main/java/com/example/docs/block/entity/ModBlockEntities.java
  reference/latest/src/main/java/com/example/docs/block/entity/custom/CounterBlockEntity.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/blockstates/counter_block.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/block/counter_block.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/models/item/counter_block.json
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/block/counter_block.png
  sidebar_translations.json
Labels: new-content, stage:ready

#240 Block Entity Renderers article
  .vitepress/sidebars/develop.ts
  develop/blocks/block-entity-renderer.md
  public/assets/develop/blocks/block_entity_renderer_1.png
  public/assets/develop/blocks/block_entity_renderer_2.png
  public/assets/develop/blocks/block_entity_renderer_3.png
  public/assets/develop/blocks/block_entity_renderer_4.png
  reference/latest/src/client/java/com/example/docs/FabricDocsBlockEntityRenderer.java
  reference/latest/src/client/java/com/example/docs/rendering/blockentity/CounterBlockEntityRenderer.java
  reference/latest/src/main/resources/fabric.mod.json
  sidebar_translations.json
Labels: new-content, stage:ready

#243 Update to 1.21.4: mod
  develop/items/first-item.md
  reference/gradle.properties
  reference/latest/src/client/java/com/example/docs/datagen/EnchantmentGenerator.java
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceAdvancementProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceRecipeProvider.java
  reference/latest/src/client/java/com/example/docs/rendering/DrawContextExampleScreen.java
  reference/latest/src/client/java/com/example/docs/rendering/HudRenderingEntrypoint.java
  reference/latest/src/client/java/com/example/docs/rendering/RenderingConceptsEntrypoint.java
  reference/latest/src/client/java/com/example/docs/sound/DynamicSoundManager.java
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/crafting_table.json
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/dirt.json
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/loom.json
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/oak_door.json
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/wheat_from_smelting_bread.json
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/wheat_from_smelting_cookie.json
  reference/latest/src/main/generated/data/fabric-docs-reference/recipe/wheat_from_smelting_hay_block.json
  reference/latest/src/main/java/com/example/docs/block/ModBlocks.java
  reference/latest/src/main/java/com/example/docs/block/entity/ModBlockEntities.java
  reference/latest/src/main/java/com/example/docs/damage/FabricDocsReferenceDamageTypes.java
  reference/latest/src/main/java/com/example/docs/damage/TaterBlock.java
  reference/latest/src/main/java/com/example/docs/effect/TaterEffect.java
  reference/latest/src/main/java/com/example/docs/event/FabricDocsReferenceEvents.java
  reference/latest/src/main/java/com/example/docs/item/ModItems.java
  reference/latest/src/main/java/com/example/docs/item/armor/ModArmorMaterials.java
  reference/latest/src/main/java/com/example/docs/item/custom/CounterItem.java
  reference/latest/src/main/java/com/example/docs/item/custom/LightningStick.java
  reference/latest/src/main/java/com/example/docs/item/tool/GuiditeMaterial.java
  reference/latest/src/main/java/com/example/docs/mixin/event/SheepEntityMixin.java
  reference/latest/src/main/java/com/example/docs/networking/payload/EngineSoundInstancePacket.java
  reference/latest/src/main/java/com/example/docs/potion/FabricDocsReferencePotions.java
Labels: correction, stage:expansion, new-version
