Repository FabricMC/fabric-docs, pull requests merged in 2024-06, with the labels that each got.

#107 Use relative links
  develop/sounds/custom.md
  develop/sounds/using-sounds.md
  index.md
Labels: improvement, merge-please

#100 Use different `ThemeConfig` for each locale
  .vitepress/config.mts
  .vitepress/i18n.ts
  README.md
  contributing.md
  crowdin.yml
  develop/index.md
  index.md
  navbar_translations.json
  package-lock.json
  package.json
  sidebar_translations.json
  translated/de_de/contributing.md
  translated/es_es/contributing.md
  translated/it_it/contributing.md
  translated/ko_kr/contributing.md
  translated/pt_br/contributing.md
  translated/ru_ru/contributing.md
  translated/uk_ua/contributing.md
  translated/vi_vn/contributing.md
  translated/zh_cn/contributing.md
  translated/zh_tw/contributing.md
Labels: framework, cleanup-stage

#113 Fix search + better locale picking.
  .vitepress/config.mts
  .vitepress/i18n.ts
Labels: merge-please, framework

#101 Add GitHub workflow for `markdownlint`
  .github/workflows/markdownlint.yml
  .markdownlint-cli2.yaml
Labels: improvement, merge-please, framework

#117 Lint fixes
  .github/workflows/markdownlint.yml
  .markdownlint-cli2.yaml
  .vscode/extensions.json
  .vscode/settings.json
  develop/codecs.md
  develop/commands/basics.md
  develop/events.md
  develop/getting-started/introduction-to-fabric-and-modding.md
  develop/items/potions.md
  develop/rendering/basic-concepts.md
  develop/rendering/particles/creating-particles.md
  package-lock.json
  package.json
  players/faq.md
  players/troubleshooting/crash-reports.md
  players/troubleshooting/uploading-logs.md
  players/updating-fabric.md
Labels: merge-please
