Repository FabricMC/fabric-docs, pull requests merged in 2025-03, with the labels that each got.

#249 Networking Guide
  .vitepress/sidebars/develop.ts
  develop/data-generation/advancements.md
  develop/data-generation/loot-tables.md
  develop/data-generation/recipes.md
  develop/data-generation/tags.md
  develop/data-generation/translations.md
  develop/networking.md
  public/assets/develop/networking/sides.png
  public/assets/develop/networking/summon-lightning.webm
  public/assets/develop/networking/use-poisonous-potato.webm
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceDataGenerator.java
  reference/latest/src/client/java/com/example/docs/network/basic/FabricDocsReferenceNetworkingBasicClient.java
  reference/latest/src/client/java/com/example/docs/network/basic/FabricDocsReferenceNetworkingBasicModelProvider.java
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/lightning_tater.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/ruby_door.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/ruby_fence.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/ruby_trapdoor.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/models/item/lightning_tater.json
  reference/latest/src/main/java/com/example/docs/networking/basic/FabricDocsReferenceNetworkingBasic.java
  reference/latest/src/main/java/com/example/docs/networking/basic/GiveGlowingEffectC2SPayload.java
  reference/latest/src/main/java/com/example/docs/networking/basic/LightningTaterItem.java
  reference/latest/src/main/java/com/example/docs/networking/basic/SummonLightningS2CPayload.java
  reference/latest/src/main/resources/assets/fabric-docs-reference/textures/item/lightning_tater.png
  reference/latest/src/main/resources/fabric.mod.json
  sidebar_translations.json
Labels: new-content, stage:ready

#302 clarify project generator page
  develop/getting-started/creating-a-project.md
Labels: correction, stage:ready

#303 Fix inconsistency in latest/FabricDocsReferenceAdvancementProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceAdvancementProvider.java
Labels: correction, stage:ready

#297 use a Markdown table in Text and Translations
  .markdownlint-cli2.yaml
  develop/text-and-translations.md
Labels: correction, stage:ready

#311 Add missing closing bracket in Creating Your First Item
  reference/latest/src/main/java/com/example/docs/item/ModItems.java
Labels: correction, stage:ready

#292 Correct `author` information
  develop/blocks/first-block.md
  develop/commands/basics.md
  develop/data-generation/advancements.md
  develop/data-generation/block-models.md
  develop/data-generation/loot-tables.md
  develop/data-generation/recipes.md
  develop/data-generation/setup.md
  develop/data-generation/tags.md
  develop/data-generation/translations.md
  develop/entities/damage-types.md
  develop/entities/effects.md
  develop/events.md
  develop/getting-started/creating-a-project.md
  develop/getting-started/setting-up-a-development-environment.md
  develop/ide-tips-and-tricks.md
  develop/items/first-item.md
  develop/items/potions.md
  develop/loom/fabric-api.md
  develop/loom/index.md
  develop/loom/options.md
  develop/loom/production-run-tasks.md
  develop/rendering/basic-concepts.md
  players/installing-fabric.md
Labels: correction, stage:ready

#293 Update Authors component
  .vitepress/theme/components/AuthorsComponent.vue
  .vitepress/theme/index.ts
  public/assets/avatater.png
  website_translations.json
Labels: stage:ready, framework

#298 refactor: use `computed` instead of `ref`
  .vitepress/theme/components/BannerComponent.vue
  .vitepress/theme/components/ColorSwatch.vue
  .vitepress/theme/components/DownloadEntry.vue
  .vitepress/theme/components/NotFoundComponent.vue
  .vitepress/theme/components/VersionSwitcher.vue
  .vitepress/theme/components/VideoPlayer.vue
Labels: stage:ready, framework

#312 Crowdin-related improvements
  .vitepress/config.mts
  .vitepress/i18n.ts
  crowdin.yml
  website_translations.json
Labels: stage:ready, framework, localization

#314 Correct Crowdin url
  .vitepress/i18n.ts
  develop/networking.md
Labels: correction, stage:ready, framework, localization
