Repository FabricMC/fabric-docs, pull requests merged in 2025-09, with the labels that each got.

#347 Update Docs to 1.21.8
  .vitepress/config.mts
  .vitepress/sidebars/develop.ts
  .vitepress/theme/components/VersionReminder.vue
  develop/blocks/block-entities.md
  develop/data-generation/block-models.md
  develop/data-generation/setup.md
  develop/data-generation/tags.md
  develop/getting-started/setting-up-a-development-environment.md
  develop/items/custom-armor.md
  develop/items/custom-tools.md
  develop/loom/index.md
  develop/networking.md
  develop/rendering/basic-concepts.md
  develop/rendering/draw-context.md
  develop/rendering/hud.md
  reference/build.gradle
  reference/gradle.properties
  reference/gradle/wrapper/gradle-wrapper.properties
  reference/latest/build.gradle
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceDamageTypesProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceItemTagProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceModelProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/internal/FabricDocsReferenceInternalModelProvider.java
  reference/latest/src/client/java/com/example/docs/rendering/DrawContextExampleScreen.java
  reference/latest/src/client/java/com/example/docs/rendering/HudRenderingEntrypoint.java
  reference/latest/src/client/java/com/example/docs/rendering/RenderingConceptsEntrypoint.java
  reference/latest/src/client/java/com/example/docs/rendering/blockentity/CounterBlockEntityRenderer.java
  reference/latest/src/gametest/java/com/example/docs/FabricDocsGameTest.java
  reference/latest/src/main/generated/assets/fabric-docs-reference/blockstates/prismarine_lamp.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/engine.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/ruby_door.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/ruby_fence.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/ruby_trapdoor.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/items/tater.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/models/block/prismarine_lamp.json
  reference/latest/src/main/generated/assets/fabric-docs-reference/models/block/prismarine_lamp_on.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/building_blocks/dirt.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/food/wheat_from_smelting_bread.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/food/wheat_from_smelting_cookie.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/food/wheat_from_smelting_hay_block.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/misc/crafting_table.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/misc/loom.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/recipes/redstone/oak_door.json
  reference/latest/src/main/java/com/example/docs/block/entity/custom/CounterBlockEntity.java
  reference/latest/src/main/java/com/example/docs/command/FabricDocsReferenceCommands.java
  reference/latest/src/main/java/com/example/docs/item/ModItems.java
  reference/latest/src/main/java/com/example/docs/item/custom/CounterItem.java
  reference/latest/src/main/java/com/example/docs/item/custom/LightningStick.java
  reference/latest/src/main/resources/fabric.mod.json
Labels: stage:verification, new-version, priority:high

#326 Project location
  develop/getting-started/creating-a-project.md
Labels: improvement, stage:cleanup, priority:medium

#361 replace remaining mentions of tickDelta with tickProgress
  develop/rendering/hud.md
Labels: correction, stage:ready

#348 Clarify that `mod-id` placeholders must be customized
  develop/getting-started/creating-a-project.md
Labels: improvement, stage:ready

#324 Items: Item Models
  .vitepress/sidebars/develop.ts
  develop/items/first-item.md
  develop/items/item-models.md
  sidebar_translations.json
Labels: new-content, stage:verification

#338 Running Game Tests
  .github/workflows/build.yml
  develop/automatic-testing.md
  reference/latest/build.gradle
Labels: improvement, stage:verification
