Repository FabricMC/fabric-docs, pull requests merged in 2025-01, with the labels that each got.

#245 Update to 1.21.4: "Getting Started" and "Blocks"
  .gitignore
  develop/blocks/block-entity-renderer.md
  develop/blocks/blockstates.md
  develop/blocks/first-block.md
  develop/getting-started/setting-up-a-development-environment.md
  reference/latest/src/main/java/com/example/docs/block/ModBlocks.java
Labels: correction, stage:ready, new-version

#248 Update to 1.21.4: "Rendering"
  develop/rendering/basic-concepts.md
  develop/rendering/draw-context.md
  develop/rendering/hud.md
  develop/rendering/particles/creating-particles.md
  reference/latest/src/client/java/com/example/docs/rendering/DrawContextExampleScreen.java
  reference/latest/src/client/java/com/example/docs/rendering/HudRenderingEntrypoint.java
  reference/latest/src/client/java/com/example/docs/rendering/RenderingConceptsEntrypoint.java
Labels: correction, stage:verification, new-version

#258 Update to 1.21.4: Niche Pages
  develop/data-generation/advancements.md
  develop/data-generation/tags.md
  develop/data-generation/translations.md
  develop/entities/damage-types.md
  reference/1.21/src/client/java/com/example/docs/datagen/util/FabricDocsReferenceInternalModelProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/FabricDocsReferenceAdvancementProvider.java
  reference/latest/src/client/java/com/example/docs/datagen/internal/FabricDocsReferenceInternalModelProvider.java
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/apple_and_beef.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/break_block_with_tool.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/break_block_with_tool_five_times.json
  reference/latest/src/main/generated/data/fabric-docs-reference/advancement/get_dirt.json
  reference/latest/src/main/java/com/example/docs/block/ModBlocks.java
  reference/latest/src/main/java/com/example/docs/item/FabricDocsReferenceItems.java
  reference/latest/src/main/java/com/example/docs/item/armor/GuiditeArmorMaterial.java
Labels: correction, new-version

#264 fix spelling mistakes
  .vitepress/sidebars/develop.ts
  .vitepress/sidebars/versioned/1.20.4.json
  .vitepress/sidebars/versioned/1.21.json
  .vitepress/theme/components/VideoPlayer.vue
  .vitepress/transform.ts
  .vitepress/update.ts
  README.md
  develop/blocks/blockstates.md
  develop/blocks/first-block.md
  develop/data-generation/recipes.md
  develop/entities/damage-types.md
  develop/entities/effects.md
  develop/ide-tips-and-tricks.md
  develop/items/custom-armor.md
  develop/items/custom-data-components.md
  develop/items/custom-enchantment-effects.md
  develop/items/custom-item-groups.md
  develop/items/custom-item-interactions.md
  develop/items/first-item.md
  develop/items/food.md
  develop/rendering/particles/creating-particles.md
  develop/sounds/custom.md
  develop/sounds/dynamic-sounds.md
  translated/it_it/develop/blocks/blockstates.md
Labels: correction, stage:ready

#269 Fix netlify preview deploy
  netlify.toml
Labels: framework

#266 Various Sitewide Fixes & Improvements.
  .vitepress/config.mts
  .vitepress/theme/CountryFlagsPolyfill.woff2
  .vitepress/theme/components/AuthorsComponent.vue
  .vitepress/theme/components/VersionReminder.vue
  .vitepress/theme/components/VersionSwitcher.vue
  .vitepress/theme/components/VideoPlayer.vue
  .vitepress/theme/index.ts
  .vitepress/theme/style.css
  .vitepress/transform.ts
  README.md
  package-lock.json
  package.json
Labels: improvement, stage:ready, framework

#274 Fix Mozilla's license URL
  README.md
Labels: correction, stage:ready
